#!/usr/bin/env python3

import os

from datetime import datetime
from datetime import timedelta

    
print('22000 days from today is:')
print (datetime.now() + timedelta(days=22000))


birthday = input("What is your birthday? YYYYMMDD \n")

#print('You will be 22000 days old on:')
print (birthday + timedelta(days=22000))

#print(datetime((int(birthday[0:4]), int(birthday[4:6]), int(birthday[6:8])) + \
#timedelta(days=22000)))
