#!/usr/bin/env python3

import random
import letters as le

color = [
    "\033[31m", 
    "\033[32m", 
    "\033[33m", 
    "\033[34m", 
    "\033[35m", 
    "\033[36m", 
    "\033[37m", 
    "\033[38m" 
    ]

def randomcolorpicker():
    pickedcolor = random.choice(color)
    return pickedcolor

def randomizer():
    while True:
        char = random.choice(le.characters)
        print(randomcolorpicker() + "\033[32m" + char, end="")

try:
    randomizer()
except(KeyboardInterrupt, EOFError):
    print("\nBinary Over")
    exit()
